version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend